# Generated by Django 5.1 on 2024-09-23 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=400, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=400, null=True)),
                ('document', models.CharField(blank=True, max_length=400, null=True)),
                ('is_driver_licence_validated', models.BooleanField(default=False)),
                ('is_document_validated', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
