# Generated by Django 5.1 on 2024-09-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Rider', 'Rider'), ('User', 'User')], default='User', max_length=10),
        ),
    ]
