# Generated by Django 5.1 on 2024-09-13 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('ride', 'Ride'), ('delivery', 'Delivery')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('dispute_approved', 'Dispute Approved')], default='pending', max_length=20)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_details', models.TextField(blank=True, null=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('dispute_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved')], max_length=50, null=True)),
                ('dispute_reason', models.TextField(blank=True, null=True)),
                ('dispute_resolution', models.TextField(blank=True, null=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_rider', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
