# Generated by Django 5.1 on 2024-11-06 01:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ridechatmessage_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('dispute_approved', 'Dispute Approved'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
