# Generated by Django 5.1 on 2024-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('dispute_approved', 'Dispute Approved')], default='pending', max_length=20),
        ),
    ]
