# Generated by Django 5.1 on 2024-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_withdrawalrequest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='reference',
            field=models.CharField(max_length=50),
        ),
    ]
