# Generated by Django 5.1 on 2024-12-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_withdrawalrequest_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='card', max_length=4),
        ),
    ]
